name: Build MO2 Helper

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-24.04 ]
        include:
          - os: windows-2022
            preset: vs2022-windows
            build_dir: vsbuild
          - os: ubuntu-24.04
            preset: linux
            build_dir: build

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Helper
        shell: pwsh
        run: |
          cmake --preset ${{ matrix.preset }} "-DCMAKE_INSTALL_PREFIX=install"

      - name: Build Helper
        run: cmake --build ${{ matrix.build_dir }} --config RelWithDebInfo

      - name: Install Helper
        run: cmake --install ${{ matrix.build_dir }} --config RelWithDebInfo

      - name: Upload Helper artifact
        uses: actions/upload-artifact@master
        with:
          name: Helper-${{ runner.os }}
          path: ./install
